//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KopotovVittaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int OrderId { get; set; }
        public int MoneyId { get; set; }
        public int Summ { get; set; }
        public int Id { get; set; }
    }
}
